use_frameworks!

target 'FeiYuePlayer_Example' do
  pod 'FeiYuePlayer', :path => '../'

  target 'FeiYuePlayer_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
  pod 'GPUImage', '~> 0.1.7'
end
